In [2]:
# 01_data_loading_and_profiling.ipynb

# If needed (Colab/new env), run once:
# !pip install pandas openpyxl matplotlib numpy jupyter

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries loaded successfully!")
print(f"Pandas version: {pd.__version__}")

# ------------------------------------------------------------------
# 1. Load raw data (update paths if needed)
# ------------------------------------------------------------------

cpi_forecast_path = r"C:\Users\abhin\OneDrive\Desktop\food-price-inflation-analysis\DATA\Raw\CPIForecast.csv"
historical_cpi_path = r"C:\Users\abhin\OneDrive\Desktop\food-price-inflation-analysis\DATA\Raw\historicalcpi.csv"

df_forecast = pd.read_csv(cpi_forecast_path)
df_cpi = pd.read_csv(historical_cpi_path)

print("Loaded successfully.")
print("CPI Forecast shape:", df_forecast.shape)
print("Historical CPI shape:", df_cpi.shape)

display(df_forecast.head(3))
display(df_cpi.head(3))

# ------------------------------------------------------------------
# 2. Profile CPI Forecast data
# ------------------------------------------------------------------

print("\n=== CPI FORECAST PROFILING ===")
print(df_forecast.info())
print("\nMissing values:")
print(df_forecast.isna().sum())
print("\nSummary statistics:")
display(df_forecast.describe(include="all").transpose())
print("\nSample rows:")
display(df_forecast.head(10))

# ------------------------------------------------------------------
# 3. Profile Historical CPI data
# ------------------------------------------------------------------

print("\n=== HISTORICAL CPI PROFILING ===")
print(df_cpi.info())
print("\nMissing values:")
print(df_cpi.isna().sum())
print("\nSummary statistics:")
display(df_cpi.describe(include="all").transpose())

print("\nTop 10 CPI items by count:")
print(df_cpi["Consumer Price Index item"].value_counts().head(10))

print("\nUnique food items (first 20):")
print(df_cpi["Consumer Price Index item"].unique()[:20])
print(f"\nTotal distinct CPI items: {df_cpi['Consumer Price Index item'].nunique()}")

print("\nAll column names:")
print(df_cpi.columns.tolist())

# ------------------------------------------------------------------
# 4. Save an initial cleaned copy (no transformations yet)
# ------------------------------------------------------------------

df_cpi.to_csv("cleaned_cpi_data_initial.csv", index=False)
print("\nSaved: cleaned_cpi_data_initial.csv")

Libraries loaded successfully!
Pandas version: 3.0.0
Loaded successfully.
CPI Forecast shape: (220, 8)
Historical CPI shape: (1122, 3)

,Top-level,Aggregate,Mid-level,Low-level,Disaggregate,Attribute,Unit,Value
0,All food,NaN,NaN,NaN,NaN,Relative importance,Percent,100.0
1,All food,NaN,NaN,NaN,NaN,Month-to-month November 2025 to December 2025,Percent change,0.6
2,All food,NaN,NaN,NaN,NaN,Year-over-year December 2024 to December 2025,Percent change,3.1

  Consumer Price Index item  Year  Percent change
0                  All food  1974            14.3
1                  All food  1975             8.5
2                  All food  1976             3.0

=== CPI FORECAST PROFILING ===
<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Top-level     220 non-null    str
 1   Aggregate     210 non-null    str
 2   Mid-level     190 non-null    str
 3   Low-level     100 non-null    str
 4   Disaggregate  50 non-null     str
 5   Attribute     220 non-null    str
 6   Unit          220 non-null    str
 7   Value         220 non-null    float64
dtypes: float64(1), str(7)
memory usage: 13.9 KB
None

Missing values:
Top-level         0
Aggregate        10
Mid-level        30
Low-level       120
Disaggregate    170
Attribute         0
Unit              0
Value             0
dtype: int64

Summary statistics:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Top-level,220,1,All food,220,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aggregate,210,2,Food at home,200,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mid-level,190,9,"Meats, poultry, and fish",70,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Low-level,100,5,Meats,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Disaggregate,50,5,Beef and veal,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Attribute,220,10,Relative importance,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unit,220,2,Percent change,198,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Value,220.0,NaN,NaN,NaN,3.292727,9.608493,-39.5,0.5,2.1,4.6,100.0

Sample rows:

,Top-level,Aggregate,Mid-level,Low-level,Disaggregate,Attribute,Unit,Value
0,All food,NaN,NaN,NaN,NaN,Relative importance,Percent,100.0
1,All food,NaN,NaN,NaN,NaN,Month-to-month November 2025 to December 2025,Percent change,0.6
2,All food,NaN,NaN,NaN,NaN,Year-over-year December 2024 to December 2025,Percent change,3.1
3,All food,NaN,NaN,NaN,NaN,Annual 2023,Percent change,5.8
4,All food,NaN,NaN,NaN,NaN,Annual 2024,Percent change,2.3
5,All food,NaN,NaN,NaN,NaN,Annual 2025,Percent change,2.9
6,All food,NaN,NaN,NaN,NaN,20-year historical average,Percent change,3.0
7,All food,NaN,NaN,NaN,NaN,Lower bound of prediction interval 2026,Percent change,0.3
8,All food,NaN,NaN,NaN,NaN,Mid point of prediction interval 2026,Percent change,3.0
9,All food,NaN,NaN,NaN,NaN,Upper bound of prediction interval 2026,Percent change,5.9

=== HISTORICAL CPI PROFILING ===
<class 'pandas.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Consumer Price Index item  1122 non-null   str
 1   Year                       1122 non-null   int64
 2   Percent change             1097 non-null   float64
dtypes: float64(1), int64(1), str(1)
memory usage: 26.4 KB
None

Missing values:
Consumer Price Index item     0
Year                          0
Percent change               25
dtype: int64

Summary statistics:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Consumer Price Index item,1122,22,All food,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,1122.0,NaN,NaN,NaN,1999.0,14.726165,1974.0,1986.0,1999.0,2012.0,2024.0
Percent change,1097.0,NaN,NaN,NaN,3.828624,5.374299,-21.1,1.0,2.9,5.6,52.4

Top 10 CPI items by count:
Consumer Price Index item
All food                    51
Food away from home         51
Food at home                51
Meats, poultry, and fish    51
Meats                       51
Beef and veal               51
Pork                        51
Other meats                 51
Poultry                     51
Fish and seafood            51
Name: count, dtype: int64

Unique food items (first 20):
<StringArray>
[                       'All food',             'Food away from home',
                    'Food at home',        'Meats, poultry, and fish',
                           'Meats',                   'Beef and veal',
                            'Pork',                     'Other meats',
                         'Poultry',                'Fish and seafood',
                            'Eggs',                  'Dairy products',
                   'Fats and oils',           'Fruits and vegetables',
     'Fresh fruits and vegetables',                    'Fresh fruits',
                'Fresh vegetables', 'Processed fruits and vegetables',
                'Sugar and sweets',     'Cereals and bakery products']
Length: 20, dtype: str

Total distinct CPI items: 22

All column names:
['Consumer Price Index item', 'Year', 'Percent change']

Saved: cleaned_cpi_data_initial.csv